### ISSUE TITLE
fails to run in official maubot docker container

### ISSUE THREAD

**Issue by williamkray** [ajkessel/reacjibot#1]
when attempting to load an instance of this plugin using the officially published maubot docker container, the following error occurs:

```
[17:36:04](file:////opt/maubot/maubot/loader/zip.py:203)ERRORmaubot.loader.zipFailed to load org.rosi-kessel.reacjibot v0.3.9
[17:36:04](file:////opt/maubot/maubot/loader/zip.py:203)ERRORmaubot.loader.zipTraceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 216, in _load
    importer.load_module(module)
  File "/opt/maubot/maubot/lib/zipimport.py", line 280, in load_module
    exec(code, mod.__dict__)
  File "/data/plugins/org.rosi-kessel.reacjibot-v0.3.9.mbp/reacjibot/__init__.py", line 1, in <module>
    from .bot import ReacjiBot
  File "/data/plugins/org.rosi-kessel.reacjibot-v0.3.9.mbp/reacjibot/bot.py", line 2, in <module>
    import emoji
ModuleNotFoundError: No module named 'emoji'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 201, in load
    return self._load(reset_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maubot/maubot/loader/zip.py", line 220, in _load
    raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module reacjibot
[17:36:04](file:////opt/maubot/maubot/management/api/middleware.py:68)ERRORmaubot.serverError in handler
[17:36:04](file:////opt/maubot/maubot/management/api/middleware.py:68)ERRORmaubot.serverTraceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 216, in _load
    importer.load_module(module)
  File "/opt/maubot/maubot/lib/zipimport.py", line 280, in load_module
    exec(code, mod.__dict__)
  File "/data/plugins/org.rosi-kessel.reacjibot-v0.3.9.mbp/reacjibot/__init__.py", line 1, in <module>
    from .bot import ReacjiBot
  File "/data/plugins/org.rosi-kessel.reacjibot-v0.3.9.mbp/reacjibot/bot.py", line 2, in <module>
    import emoji
ModuleNotFoundError: No module named 'emoji'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/maubot/maubot/management/api/middleware.py", line 49, in error
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maubot/maubot/management/api/instance.py", line 83, in update_instance
    return await _create_instance(instance_id, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maubot/maubot/management/api/instance.py", line 59, in _create_instance
    await instance.start()
  File "/opt/maubot/maubot/instance.py", line 362, in start
    cls = await self.loader.load()
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maubot/maubot/loader/zip.py", line 201, in load
    return self._load(reset_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maubot/maubot/loader/zip.py", line 220, in _load
    raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module reacjibot
```

seems like it depends on a python library called `emoji` that is not contained in the default container image... i would recommend avoiding this dependency and sticking to supporting the unicode emojis instead of trying to translate them from strings. e.g.:

```
mapping:
  "train": "public_transportation"
```

should just be:

```
mapping:
  "🚋": "public_transportation"
```

most clients support copying the emoji to the clipboard, and then you can paste it directly into the instance's configuration file.

**Comment by ajkessel** [comment]
OK, fair enough. I thought it was handy to be able to use the short name but I can see why it would be a problem to require an uncommon library. I've fixed the plugin per your recommendation with [f46399fed4eaa7076985a950f72b686c30e49500](https://github.com/ajkessel/reacjibot/commit/f46399fed4eaa7076985a950f72b686c30e49500)
